spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleshoppingdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or create, validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

joinfaces:
  faces:
    PROJECT_STAGE: Development
  primefaces:
    theme: overcast

logging:
  level:
    org.springframework.security: DEBUG
